workspace:
  base: /test
  path: bw_d7

services:
  web:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    environment:
    - DOCUMENT_ROOT=/test/bw_d7
#  mysql:
#    image: percona/percona-server:5.6
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

pipeline:
  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    volumes:
#    - /cache:/cache
    commands:
      - echo "testing WIP RUNNING STEP Composer-install-lowest"
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

matrix:
  PHP_VERSION:
  - 5.6
  - 7.1
  - 7.2
  COMPOSER_BOUNDARY:
  - lowest
  - highest
